"""
GitHub Router
-------------
Endpoints for publishing to and browsing the Precedent GitHub repository.
"""

import logging
from fastapi import APIRouter, HTTPException
from models.schemas import PublishResponse, RepositoryResponse
from services import github_service, supabase_service

logger = logging.getLogger(__name__)
router = APIRouter()


@router.post("/publish/{submission_id}", response_model=PublishResponse)
async def publish_to_github(submission_id: str):
    """
    Commit analysis artifacts for a submission to the GitHub repository.
    """
    # Fetch submission + related data
    try:
        sub = supabase_service.get_submission(submission_id)
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"DB error: {e}")

    if not sub:
        raise HTTPException(status_code=404, detail="Submission not found.")

    # For MVP: build topic-predictions.md content from DB
    try:
        topics = supabase_service.get_topics(sub["subject_id"])
    except Exception:
        topics = []

    # Build topic-predictions.md
    md_lines = [
        "# Precedent — Topic Predictions\n",
        f"**Subject:** {sub.get('subject_id', 'Unknown')}\n",
        f"**Analysis Date:** {sub.get('created_at', 'N/A')}\n\n",
        "## Ranked Topics\n\n",
        "| Rank | Topic | Frequency Score | Marks Weight |\n",
        "|------|-------|-----------------|---------------|\n",
    ]
    for i, t in enumerate(topics, 1):
        freq = f"{t['frequency_score'] * 100:.0f}%"
        marks = f"{t['marks_weight'] * 100:.0f}%"
        md_lines.append(f"| {i} | {t['name']} | {freq} | {marks} |\n")

    md_content = "".join(md_lines).encode("utf-8")

    # Get institution/course/subject names (best-effort)
    institution = "PSIT College of Engineering"
    course = "B.Tech CSE"
    subject = sub.get("subject_id", "Unknown Subject")

    files = [
        ("analysis/topic-predictions.md", md_content),
        ("analysis/README.md", f"# {subject}\n\nAnalysis generated by [Precedent](https://precedent.vercel.app)\n".encode()),
    ]

    result = github_service.commit_analysis(
        institution=institution,
        course=course,
        subject=subject,
        files=files,
        commit_message=f"feat: add analysis for {subject}",
    )

    if not result.get("success"):
        raise HTTPException(
            status_code=500,
            detail=f"GitHub publish failed: {result.get('error', 'Unknown error')}"
        )

    return PublishResponse(
        success=True,
        github_url=result["github_url"],
        commit_sha=result["commit_sha"],
        files_committed=result["files_committed"],
    )


@router.get("/repository", response_model=RepositoryResponse)
async def get_repository():
    """Browse the Precedent GitHub repository tree."""
    try:
        tree = github_service.get_repository_tree()
    except Exception as e:
        logger.error(f"Repository fetch failed: {e}")
        # Return seeded fallback data so the UI doesn't break
        return RepositoryResponse(
            institutions=[
                {
                    "name": "PSIT College of Engineering",
                    "courses": [{"name": "B.Tech CSE", "subjects": [
                        {"name": "Database Management Systems", "path": "precedent-repository/psit/btech-cse/dbms", "github_url": "#"}
                    ]}],
                }
            ],
            total_subjects=1,
            total_institutions=1,
        )

    return RepositoryResponse(**tree)
