import React, { useEffect, useState } from 'react'
import { useParams, Link } from 'react-router-dom'
import { ArrowLeft, FileText, Download, Printer, CheckCircle, Sparkles } from 'lucide-react'
import MockPaperViewer from '../components/MockPaperViewer'
import { getMockPapers } from '../lib/api'
import type { MockPaper } from '../lib/types'

export default function MockPapers() {
  const { subjectId } = useParams<{ subjectId: string }>()

  const [papers, setPapers] = useState<MockPaper[]>([])
  const [activeTab, setActiveTab] = useState<number>(0)
  const [loading, setLoading] = useState<boolean>(true)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    if (!subjectId) return

    // 1. Check session storage cache
    const cached = sessionStorage.getItem(`precedent_result_${subjectId}`)
    if (cached) {
      try {
        const parsed = JSON.parse(cached)
        if (parsed.papers && parsed.papers.length > 0) {
          setPapers(parsed.papers)
          setLoading(false)
          return
        }
      } catch (e) {
        console.error(e)
      }
    }

    // 2. Fetch from backend
    getMockPapers(subjectId)
      .then(res => {
        if (res && res.papers) {
          setPapers(res.papers)
        }
      })
      .catch(err => {
        console.error(err)
        setError('Could not retrieve simulated mock papers. Please run an analysis first.')
      })
      .finally(() => setLoading(false))
  }, [subjectId])

  return (
    <div className="pt-24 pb-20 px-4 sm:px-6 lg:px-8 max-w-5xl mx-auto space-y-6">
      {/* Navigation & Header */}
      <div className="print:hidden">
        <Link
          to={`/dashboard/${subjectId}`}
          className="inline-flex items-center gap-1.5 text-xs font-semibold text-navy-500 hover:text-navy mb-2"
        >
          <ArrowLeft size={14} /> Back to Pattern Matrix
        </Link>
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div>
            <h1 className="font-display text-3xl sm:text-4xl font-bold text-navy">
              Pattern-Synthesized Mock Examination Papers
            </h1>
            <p className="text-sm text-navy-600 mt-1">
              Generated by mirroring the structural sections, marks distribution, and question taxonomies of your uploaded PYQs.
            </p>
          </div>
          <Link
            to={`/planner/${subjectId}`}
            className="btn-outline text-xs py-2 px-4 inline-flex items-center gap-1.5 flex-shrink-0"
          >
            Revision Planner
          </Link>
        </div>
      </div>

      {loading ? (
        <div className="p-16 text-center text-navy-400">
          <div className="w-10 h-10 border-4 border-navy-200 border-t-navy rounded-full animate-spin mx-auto mb-3" />
          <p className="text-sm font-medium">Loading generated examination papers...</p>
        </div>
      ) : error || papers.length === 0 ? (
        <div className="card text-center p-12 space-y-3">
          <FileText size={36} className="mx-auto text-navy-300" />
          <h3 className="font-display text-lg font-bold text-navy">No Mock Papers Available</h3>
          <p className="text-xs text-navy-500 max-w-md mx-auto">
            {error || 'No mock papers have been synthesized for this subject yet.'}
          </p>
          <Link to="/upload" className="btn-primary text-xs inline-block py-2 px-5 mt-2">
            Upload & Analyze PYQs
          </Link>
        </div>
      ) : (
        <div className="space-y-6">
          {/* Paper Selector Tabs */}
          <div className="flex items-center gap-2 border-b border-navy-100 pb-2 print:hidden">
            {papers.map((p, idx) => (
              <button
                key={idx}
                onClick={() => setActiveTab(idx)}
                className={`flex items-center gap-2 px-4 py-2.5 rounded-xl text-xs font-semibold transition-all duration-200 ${
                  activeTab === idx
                    ? 'bg-navy text-white shadow-xs'
                    : 'bg-white text-navy-600 hover:bg-navy-50 border border-navy-100'
                }`}
              >
                <FileText size={14} />
                <span>Simulated Mock Paper Set 0{p.paper_number || idx + 1}</span>
              </button>
            ))}
          </div>

          {/* Active Mock Paper Component */}
          {papers[activeTab] && (
            <MockPaperViewer
              paper={papers[activeTab]}
              subjectId={subjectId || ''}
            />
          )}
        </div>
      )}
    </div>
  )
}
